In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
import imageio
import numpy as np

In [34]:
import sklearn.metrics

def flatten(nested_list):
    return np.asarray(nested_list).flatten()

def OIS(label, output):
	label_matrix = flatten(label.astype('float'))
	label_matrix = (label_matrix == 255)
	output_matrix = flatten(output.astype('float'))
	OIS_results = []
	for threshold in range(256):
		threshold_matrix = (output_matrix >= threshold)
		precision, recall, OIS_result, _ = sklearn.metrics.precision_recall_fscore_support(label_matrix, threshold_matrix, average='binary')
# 		print(precision, recall, OIS_result, _)
		print(sklearn.metrics.confusion_matrix(label_matrix, threshold_matrix))
		OIS_results.append(OIS_result)
		print(OIS_result)
	
	return max(OIS_results)

In [35]:
import time

gdrive_path = '../../'
labels_path = gdrive_path + "datasets/BIPED/edges/edge_maps/train/rgbr/real/"
output_path = gdrive_path + "Canny Detector/Canny-Edge BIPED/canny_output/"
save_path = gdrive_path + "Evaluation Metrics/Optimal Image Scale (OIS)/Canny_BIPED.txt"

print(os.listdir(gdrive_path))
img_name = os.listdir(labels_path)
outputs = os.listdir(output_path)

if os.path.exists(save_path):
  save_file = open(save_path, 'r+')
else:
  save_file = open(save_path, 'w+')
lines = save_file.readlines()

totalOIS = 0
img_name.sort()
outputs.sort()
assert len(img_name) == len(outputs)

for i in range(len(img_name)):
  if i < len(lines):
    ois = float(lines[i].split(',')[1])
  else:
    assert img_name[i].split('.')[0] == outputs[i].split('.')[0]
    label_img = imageio.imread(labels_path + img_name[i])
    output_img = imageio.imread(output_path + outputs[i])
    ois = OIS(label_img, output_img)
    save_file.write(img_name[i].split('.')[0] + ',' + str(ois) + '\n')

  totalOIS += ois

  t = time.localtime()
  current_time = time.strftime("%H:%M:%S", t)
  print(current_time, img_name[i], ois)

averageOIS = totalOIS / len(img_name)
print("OIS is " + str(averageOIS) + " over " + str(len(img_name)) + " images.")

['benchmarks', 'datasets', '.git', 'README.md', 'DexiNed Detector', 'Canny Detector', 'Evaluation Metrics']
[[     0 893709]
 [     0  27891]]
0.058749372031962385
[[774037 119672]
 [ 15815  12076]]
0.15129135111094408
[[783538 110171]
 [ 16623  11268]]
0.15091408290363628
[[792729 100980]
 [ 17350  10541]]
0.15122084182136403
[[801633  92076]
 [ 18004   9887]]
0.1522787130161566
[[809280  84429]
 [ 18550   9341]]
0.15355783694035066
[[815862  77847]
 [ 19036   8855]]
0.15454696185630887
[[822065  71644]
 [ 19481   8410]]
0.15582009356616794
[[827398  66311]
 [ 19843   8048]]
0.15741809290953543
[[831999  61710]
 [ 20161   7730]]
0.15883942423277272
[[836485  57224]
 [ 20499   7392]]
0.15981493292399493
[[840452  53257]
 [ 20776   7115]]
0.1612227094025809
[[844079  49630]
 [ 21041   6850]]
0.16237806829360799
[[847227  46482]
 [ 21260   6631]]
0.16372031010814284


KeyboardInterrupt: 